directive:
    BITS NUMBER
    | LBRACKET BITS NUMBER RBRACKET
    | SECTION LABEL
    | GLOBAL LABEL
    | GLOBAL LABEL COMMA LABEL
    | GLOBAL LABEL COMMA LABEL COMMA LABEL
    | EXTERN LABEL
    | LABEL EQU NUMBER
    | LABEL COLON RESB NUMBER
    | LABEL COLON RESW NUMBER
    | LABEL COLON RESD NUMBER
    | LABEL COLON RESQ NUMBER
    | LABEL RESB NUMBER
    | LABEL RESW NUMBER
    | LABEL RESD NUMBER
    | LABEL RESQ NUMBER
    ;
