#include <stdio.h>
#include <string.h>
#include "globals.h"

/* Declarations generated by yacc */
int yyparse(void);
extern FILE *yyin;
extern int lineno;
extern char *flush_line(void);

void yyerror(const char *s) {
    fprintf(stderr, "\n");
    fprintf(stderr, "=== SYNTAX ERROR ===\n");
    fprintf(stderr, "Line %d: %s\n", lineno, s);
    if (strlen(last_mnemonic) > 0)
        fprintf(stderr, "Last recognized mnemonic: %s\n", last_mnemonic);
    fprintf(stderr, "\n");
}

int main(int argc, char *argv[]) {
    if (argc > 1) {
        yyin = fopen(argv[1], "r");
        if (!yyin) {
            perror("fopen");
            return 1;
        }
    }

    int result = yyparse();
    if (result != 0) return result;
    return 0;
}
